baseURL = "http://theme.catosplace.co.nz/"
languageCode = "en-us"
title = "Catosplace Hugo Theme"
theme = "catosplace"

# Google Analytics
googleAnalytics = "UA-157870869-1"

[[menu.main]]
name = "About"
url = "/about"

[[menu.main]]
name = "Blog"
url = "/blog"

[[menu.main]]
name = "Contact"
url = "/contact"

[[menu.social]]
name = "Twitter"
url = "https://twitter.com/catosplace_nz"
pre = "twitter"

[[menu.footer]]
name = "About"
url = "/about"

[[menu.footer]]
name = "Contact"
url = "/contact"

[[menu.footer]]
name = "Privacy"
url = "/privacy"

[markup.goldmark.renderer]
unsafe = true

[params]
# MetaData
description = "Catosplace Hugo Theme"

author = "Pete Sellars"
authorImage = "/images/pete.png"