baseURL = "http://theme.catosplace.co.nz/"
languageCode = "en-us"
title = "Catosplace Hugo Theme"
theme = "catosplace"

# Google Analytics
googleAnalytics = "UA-157870869-1"

[params]
# MetaData
description = "Catosplace Hugo Theme"